version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "flood-risk-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3h3zqbhhdubd"
s3_prefix = "flood-risk-stack"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
