version: 2
updates:
  - package-ecosystem: "pip"
    labels:
        - "Dep update"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
