name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Frezze packages
        run: pipenv lock -r > code/requirements.txt
      - name: Get SAM CLI
        run: pip install --user aws-sam-cli
      - name: Build bundle
        run: sam build --use-container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: sam deploy
        env:
          KORTFORSYNINGEN: ${{ secrets.AWS_ACCESS_KEY_ID }}
          GEO_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
