name: Runs deployment steps and analyses code
'on':
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: '${{ secrets.docker_user }}'
          password: '${{ secrets.docker_token }}'
          repository: rotendahl/flood_risk
          tag_with_sha: true
          tag_with_ref: true
