name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_SIZE: 800
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install packages
        run: pipenv install --deploy --dev --system
      
      - name: Checking black
        run: black --check .
      - name: Checking Flake8
        run: flake8 --max-complexity 8 .
      
      - name: Run tests
        run: python -m unittest
        env:
          GEO_KEY: ${{ secrets.GEO_KEY }}
          DATAFORDELEREN: ${{ secrets.DATAFORDELEREN}}
          DATAFORSYNINGEN: ${{ secrets.DATAFORSYNINGEN}}
       
      - name: Creating coverage
        run:  
        env:
          GEO_KEY: ${{ secrets.GEO_KEY }}
          DATAFORDELEREN: ${{ secrets.DATAFORDELEREN}}
          DATAFORSYNINGEN: ${{ secrets.DATAFORSYNINGEN}}

      - name: Uploading Coverage
        run: coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

