name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_SIZE: 800
      GEO_KEY: ${{ secrets.GEO_KEY }}
      KORTFORSYNINGEN: ${{ secrets.KORTFORSYNINGEN }}

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Build image
        run: docker build -t flood_risk .
      - name: Run tests
        run: |
          docker run \
              -e KORTFORSYNINGEN -e GEO_KEY -e IMAGE_SIZE \
                flood_risk pipenv run python -m unittest

      # - name: Creating coverage
      #   run: |
      #     docker run \
      #         -e KORTFORSYNINGEN -e GEO_KEY -e IMAGE_SIZE \
      #         flood_risk pipenv run coverage run --source=. -m unittest
      #
      # - name: Uploading Coverage
      #   run: |
      #     docker run \
      #         -e COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}\
      #         flood_risk pipenv run coveralls
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Checking black
        run: docker run flood_risk pipenv run black --check .
      - name: Checking Flake8
        run: docker run flood_risk pipenv run flake8 --max-complexity 8 .
